---
title: RISE UP Physical Therapy
collections:
  hometiles:
    title: Hometiles
    output: true
    permalink: "/:path/"
  physical-therapy:
    title: Physical Therapy
    output: true
  posts:
    title: Posts
    output: true
  stafftiles:
    title: Stafftiles
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    categories: blog
    featured-image: ''
    permalink: "/:categories/:title"
    description: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: ''
url: https://www.riseup-physicaltherapy.com/
email: rachel@riseup-physicaltherapy.com
description: RISE UP Physical Therapy provides physical therapy services to patients throughout Northern Virginia. Schedule your appointment today!
logo: uploads/logos/rise-up-logo.svg
markdown: kramdown
permalink: pretty
include:
- _redirects
home-link-in-menu: true
